# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_text', models.CharField(max_length=200)),
                ('port_text', models.CharField(max_length=200)),
                ('policy_text', models.CharField(max_length=200)),
                ('URL_text', models.CharField(max_length=200)),
                ('VS_text', models.CharField(max_length=200)),
                ('pool_text', models.CharField(max_length=2000)),
                ('business_text', models.CharField(max_length=200)),
                ('idc_text', models.CharField(max_length=200)),
                ('refresh_time', models.DateTimeField(verbose_name='date published')),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
    ]
