# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_f5'),
    ]

    operations = [
        migrations.AddField(
            model_name='f5',
            name='idc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
