# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0004_auto_20170605_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F5',
        ),
    ]
