# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='Threat_type',
            field=models.PositiveIntegerField(default=29),
        ),
    ]
