# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permissions_Detail', models.CharField(max_length=200)),
                ('Permissions_Example', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='System_Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Name', models.CharField(max_length=200)),
                ('System_Url', models.URLField()),
                ('System_Owner', models.CharField(max_length=200)),
                ('Permission_Name', models.CharField(max_length=200)),
                ('Permission_index', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='permissions',
            name='Permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_permissions.System_Permissions'),
        ),
    ]
