# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-20 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_permissions', '0002_auto_20190320_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission_Detail', models.CharField(max_length=200)),
                ('Permission_Example', models.CharField(max_length=200)),
                ('Permission_Picture', models.ImageField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='System_Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Name', models.CharField(max_length=200)),
                ('System_Url', models.URLField()),
                ('System_Owner', models.CharField(max_length=200)),
                ('Permission_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='permissions',
            name='Permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_permissions.System_Permissions'),
        ),
    ]
